version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_PASSWORD: kien123
      MYSQL_ROOT_PASSWORD: kien123
      MYSQL_DATABASE: laptop
      MYSQL_USER: user
    ports:
      - "4444:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - mynetwork
  server: 
    build:
      context: ./be_ltw
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_SYNC: true
      DB_USERNAME: root
      DB_PASSWORD: kien123
      DB_DATABASE: laptop
    ports:
      - "5000:5000"
    networks:
      - mynetwork
  fe: 
    build:
      context: ./fe-ttcs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - mynetwork
volumes:
  db:
    driver: local
networks:
  mynetwork:
    driver: bridge